<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/05/06 18:06:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=blog',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
