<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Indirizzo', 'doctrine');

/**
 * BaseIndirizzo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $via
 * @property string $indirizzo_id
 * @property Utenti $Utente
 * 
 * @method integer   getId()           Returns the current record's "id" value
 * @method string    getVia()          Returns the current record's "via" value
 * @method string    getIndirizzoId()  Returns the current record's "indirizzo_id" value
 * @method Utenti    getUtente()       Returns the current record's "Utente" value
 * @method Indirizzo setId()           Sets the current record's "id" value
 * @method Indirizzo setVia()          Sets the current record's "via" value
 * @method Indirizzo setIndirizzoId()  Sets the current record's "indirizzo_id" value
 * @method Indirizzo setUtente()       Sets the current record's "Utente" value
 * 
 * @package    sf2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIndirizzo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('indirizzo');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('via', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('indirizzo_id', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Utenti as Utente', array(
             'local' => 'id',
             'foreign' => 'indirizzo_id'));
    }
}