<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/04/26 10:01:16

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sf2',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
