<?php

/**
 * BlogArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BlogArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BlogArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BlogArticle');
    }
}