<?php

/**
 * IndirizzoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IndirizzoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IndirizzoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Indirizzo');
    }
}