<?php

/**
 * BaseUtente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nome
 * 
 * @method integer getId()   Returns the current record's "id" value
 * @method string  getNome() Returns the current record's "nome" value
 * @method Utente  setId()   Sets the current record's "id" value
 * @method Utente  setNome() Sets the current record's "nome" value
 * 
 * @package    sf2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUtente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('utente');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('nome', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}