<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/05/06 21:35:56

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=prova3',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
