<?php

/**
 * UtentiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UtentiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UtentiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Utenti');
    }
}