<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2018/05/01 21:33:44
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => 'C:/xampp5/htdocs/sf2/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'baseformfilterdoctrine' => 'C:/xampp5/htdocs/sf2/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'baseform' => 'C:/xampp5/htdocs/sf2/lib/form/BaseForm.class.php',
  'baseformdoctrine' => 'C:/xampp5/htdocs/sf2/lib/form/doctrine/BaseFormDoctrine.class.php',

  // project_model
  'article' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/Article.class.php',
  'articletable' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/ArticleTable.class.php',
  'basearticle' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/base/BaseArticle.class.php',
  'baseblogarticle' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/base/BaseBlogArticle.class.php',
  'baseblogcomment' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/base/BaseBlogComment.class.php',
  'basecomment' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/base/BaseComment.class.php',
  'baseutente' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/base/BaseUtente.class.php',
  'baseutenti' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/base/BaseUtenti.class.php',
  'blogarticle' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/BlogArticle.class.php',
  'blogarticletable' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/BlogArticleTable.class.php',
  'blogcomment' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/BlogComment.class.php',
  'blogcommenttable' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/BlogCommentTable.class.php',
  'comment' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/Comment.class.php',
  'commenttable' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/CommentTable.class.php',
  'utente' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/Utente.class.php',
  'utentetable' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/UtenteTable.class.php',
  'utenti' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/Utenti.class.php',
  'utentitable' => 'C:/xampp5/htdocs/sf2/lib/model/doctrine/UtentiTable.class.php',

  // application
  'myuser' => 'C:/xampp5/htdocs/sf2/apps/frontend/lib/myUser.class.php',

  // modules
);
