<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('BlogArticle', 'doctrine');

/**
 * BaseBlogArticle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $content
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $BlogComment
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getTitle()       Returns the current record's "title" value
 * @method string              getContent()     Returns the current record's "content" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Doctrine_Collection getBlogComment() Returns the current record's "BlogComment" collection
 * @method BlogArticle         setId()          Sets the current record's "id" value
 * @method BlogArticle         setTitle()       Sets the current record's "title" value
 * @method BlogArticle         setContent()     Sets the current record's "content" value
 * @method BlogArticle         setCreatedAt()   Sets the current record's "created_at" value
 * @method BlogArticle         setUpdatedAt()   Sets the current record's "updated_at" value
 * @method BlogArticle         setBlogComment() Sets the current record's "BlogComment" collection
 * 
 * @package    sf2
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBlogArticle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog_article');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('BlogComment', array(
             'local' => 'id',
             'foreign' => 'article_id'));
    }
}