Utenti:
  connection: doctrine
  tableName: utenti
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nome:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    cognome:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  relations:
      Indirizzo:
        class: Indirizzo
        local: indirizzo_id
        foreign: id
        foreignAlias: Utente
        foreignType: one
        type: one
Indirizzo:
  connection: doctrine
  tableName: indirizzo
  columns:
    id:
      type: integer(8)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    via:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    indirizzo_id:
          type: string()
          fixed: false
          unsigned: false
          primary: false
          notnull: false
          autoincrement: false
  relations:
      Utente:
        class: utenti
        local: indirizzo_id
        foreign: id
        foreignAlias: Utenti
        foreignType: one
        type: one
